### ISSUE TITLE
Latest docker build falling over

### ISSUE THREAD

**Issue by LloydGriffiths** [alex/letsencrypt-aws#102]
Today we pulled the latest image and saw the container fall over with the following error:

```
Traceback (most recent call last):
  File "letsencrypt-aws.py", line 9, in <module>
    import acme.jose
ImportError: No module named jose
```

I'm also able to recreate this by running `docker run -it alexgaynor/letsencrypt-aws`.

I've built the container locally and it seems to run OK. After looking at automated build on Dockerhub, it appears the latest build is stuck in `Queued` - maybe re-triggering the build would fix this?

**Comment by alex** [comment]
Should be fixed now.
