### ISSUE TITLE
Invalid length for parameter ServerCertificateName, value: 144, valid range: 1-128

### ISSUE THREAD

**Issue by mtwalsh** [alex/letsencrypt-aws#18]
Hi,

If you try to generate a certificate with a larger number of domains so 6 or more, because of how the certificate is named (concatenating the domain names) it exceeds the valid length of the ServerCertificateName parameter.

**Comment by stephenmuss** [comment]
I've run into this problem too.

**Comment by alex** [comment]
Oof. From a maintainability perspect, do either of you have preferences for how they should be named?
