### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by jcderose** [alex/letsencrypt-aws#23]
My `LETSENCRYPT_AWS_CONFIG` file lives in `/home/user/my-le-folder/letsencrypt-aws/LETSENCRYPT_AWS_CONFIG.json`. I've exported this environment variable in `~/.profile` and manually on the command line within my venv. However, I get this error:

```
(le-aws) $ python letsencrypt-aws.py update-certificates
2016-02-02 18:54:50 [startup]
Traceback (most recent call last):
  File "letsencrypt-aws.py", line 486, in <module>
    cli()
  File "/home/user/my-le-folder/le-aws/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/my-le-folder/le-aws/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/user/my-le-folder/le-aws/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/my-le-folder/le-aws/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/my-le-folder/le-aws/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "letsencrypt-aws.py", line 425, in update_certificates
    config = json.loads(os.environ["LETSENCRYPT_AWS_CONFIG"])
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

Here's my `LETSENCRYPT_AWS_CONFIG.json` file:

```
{
    "domains": [
        {
            "elb": {
                "name": "elb-name"
            },
            "hosts": ["ec2-host-name"],
            "key_type": "rsa"
        }
    ],
    "acme_account_key": "/home/user/my-le-folder/le-cert-pem.key"
}
```

**Comment by alex** [comment]
So, that text is valid JSON, and as you can see we don't do anything more than call `json.loads` would it be helpful if the value being used was included in the traceback?

**Comment by jcderose** [comment]
Yes, or possibly using `simplejson.loads` for a more detailed error message.

**Comment by dottodot** [comment]
I'm getting the same error. Is this a bug or am I doing something wrong?

**Comment by alex** [comment]
Probably you're doing something wrong, but there should be a much better
error message :-)

Alex

On Wed, Feb 3, 2016 at 10:38 AM, Marcus Williams notifications@github.com
wrote:

> I'm getting the same error. Is this a bug or am I doing something wrong?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/alex/letsencrypt-aws/issues/23#issuecomment-179297880
> .

## 

"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by ahamilton9** [comment]
Had the same issue. From what I could tell json.loads() wants a JSON string, not a path. So i switched the line to use json.load() which wants a file handle, and used open() on the path in the environment variable. Worked fine.

**Comment by alex** [comment]
The environement variable should not contain a path to a file, it should
contain the JSON itself.

On Wed, Feb 3, 2016 at 1:08 PM, Andrew Hamilton notifications@github.com
wrote:

> From what I could tell json.loads() wants a JSON string, not a path. so i
> switched the line to use json.load() which wants a file handle, and used
> open() on the environment variable name. Worked fine.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/alex/letsencrypt-aws/issues/23#issuecomment-179382459
> .

## 

"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by ahamilton9** [comment]
Well that makes more sense. Maybe I wasn't the only one? Guess when I saw a block of JSON I expected the variable to be pointing to a file, not fed the entire block.

**Comment by jcderose** [comment]
Yeah @ahamilton9 I read it the same way.

@alex to confirm, the `LETSENCRYPT_AWS_CONFIG` environment variable should be fed the entire `LETSENCRYPT_AWS_CONFIG.json` file, rather than pointing to the file itself?

**Comment by alex** [comment]
Yup, the environment variable should contain the JSON itself.
