### ISSUE TITLE
'acme' package version 0.3.0 broke the script

### ISSUE THREAD

**Issue by ahamilton9** [alex/letsencrypt-aws#24]
On my system, I was running into this error:

``` python
Traceback (most recent call last):
  File "letsencrypt-aws.py", line 8, in <module>
    import acme.client
  File "/usr/local/lib/python2.7/dist-packages/acme/client.py", line 29, in <module>
    requests.packages.urllib3.contrib.pyopenssl.inject_into_urllib3()
AttributeError: 'module' object has no attribute 'packages'
```

Couldn't figure it out, so I checked the dates on the acme package and saw it was recently updated, downgraded with this set of commands, and now we're working again:

``` sh
pip uninstall acme
pip install -Iv acme==0.2.0
```

Just a heads up.

**Comment by alex** [comment]
The `requirements.txt` specifies the version of `acme` which is required.

**Comment by ahamilton9** [comment]
I guess if I had know that this was a thing: `pip install -r requirements.txt`

I wouldn't have had as much trouble, but it's not in the README, and I've never seen this done before. Very confusing.
