### ISSUE TITLE
Multiple ELBs

### ISSUE THREAD

**Issue by alexbilbie** [alex/letsencrypt-aws#25]
The README says the following:

> `letsencrypt-aws` takes a list of ELBs, and which hosts you want them to be able to serve

To clarify, can I pass in an array of ELB names as you can with domain names?

**Comment by alex** [comment]
No, however you can list multiple ELBs in the `domains` key of `LETSENCRYPT_AWS_CONFIG`.

**Comment by alexbilbie** [comment]
Thanks, I'd overlooked that the domains value was an array of objects

**Comment by alex** [comment]
If there's something we could do to make the docs more clear let me know!
