### ISSUE TITLE
Using a separate domain

### ISSUE THREAD

**Issue by wteiken** [alex/letsencrypt-aws#3]
Just a quick thought:  On my side (I manage my own DNS servers) I did a split between the DNS domain the cert is for and the domain the authorizations are in using CNAMEs (so _acme-challenge.www.example.com IN CNAME www.example.com.acme.example.com).  This allows me to have static DNS entries for everything except one domain that contains all validations.

This allows me to have different ACLs on the account that can create validations and the account that can actually manage the DNS.  And in my case the keys are additionally protected by DANE (so changing the cert by itself would not allow use of arbitrary keys).

Just wondering if route53 can do the same thing (different ACLs for different users managing different domains) and if it's worth it implementing a mapping from the verification name as returned by the API to some other name.

**Comment by alex** [comment]
You can use IAM to give different credentials permissions on different hosted zones, I see no reason you couldn't create a hosted zones for just `_acme-challenge.<your domains>` and that would accomplish what you want. This question is probably better for a general AWS forum though.
