### ISSUE TITLE
Using an excrypted key in S3 as suggested by the README results in an error

### ISSUE THREAD

**Issue by paul** [alex/letsencrypt-aws#31]
I followed the instructions as suggested, with my key encrypted using S3 + AWS KMS, but when I try to run the command using that s3:// url, I get an error:

```
botocore.exceptions.ClientError: An error occurred (InvalidArgument) when calling the GetObject operation: Requests specifying Server Side Encryption with AWS KMS managed keys require AWS Signature Version 4.
```

I did the `pip install -r requirements.txt`, looks like I ended up with `boto3 (1.2.6)`, which looks like the latest.

**Comment by alex** [comment]
Ooof. I'm not sure what to do about this. :-(

**Comment by paul** [comment]
Hi fellow first-name github user. I ended up writing my own similar tool using Ruby, since I'm more familiar with it. Feel free to close this if you can't reproduce it, since I probably also won't investigate further myself.
