### ISSUE TITLE
DNS and LB in different accounts

### ISSUE THREAD

**Issue by kickino** [alex/letsencrypt-aws#36]
Hi!
I have the requirement to actually have a centralized DNS in one AWS account, and the load balancer in another account.
With the current approach it seems that I can have only one account configured.

Is there a workaround to specify two access keys for DNS and LB separately?

Thanks a lot in advance.
Best Regards,
   Sebastian

**Comment by alex** [comment]
Not without manually editing the code. For now this issue is probably a wontfix.

**Comment by keichan34** [comment]
@kickino my 2 cents: I haven't tried this yet, so I don't know if it works with Route 53 in particular, but it is possible to [delegate certain permissions cross-account](docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_policy-examples.html). Using this, you may be able to get access to the DNS and LB using the same account.
