### ISSUE TITLE
installing requirements fails

### ISSUE THREAD

**Issue by Esardes** [alex/letsencrypt-aws#37]
Hello and first of all thanks for that tool
`sudo /usr/local/bin/pip install -r requirements.txt` fails with what seems to be an openSSL issue

` writing src/cryptography.egg-info/PKG-INFO
    writing top-level names to src/cryptography.egg-info/top_level.txt
    writing dependency_links to src/cryptography.egg-info/dependency_links.txt
    writing entry points to src/cryptography.egg-info/entry_points.txt
    warning: manifest_maker: standard file '-c' not found

```
reading manifest file 'src/cryptography.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'docs/_build'
warning: no previously-included files matching '*' found under directory 'vectors'
writing manifest file 'src/cryptography.egg-info/SOURCES.txt'
running build_ext
generating cffi module 'build/temp.linux-x86_64-2.7/_padding.c'
creating build/temp.linux-x86_64-2.7
generating cffi module 'build/temp.linux-x86_64-2.7/_constant_time.c'
generating cffi module 'build/temp.linux-x86_64-2.7/_openssl.c'
building '_openssl' extension
creating build/temp.linux-x86_64-2.7/build
creating build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/_openssl.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_openssl.o
build/temp.linux-x86_64-2.7/_openssl.c:423:27: fatal error: openssl/e_os2.h: No such file or directory
 #include <openssl/e_os2.h>
                           ^
compilation terminated.
error: command 'gcc' failed with exit status 1

----------------------------------------
```

Command "/usr/bin/python2.7 -u -c "import setuptools, tokenize;**file**='/tmp/pip-build-3NcnLy/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-eE19gE-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-3NcnLy/`

Thanks a lot for your help!
(Alternatively, would you be kind to write a line in the README about how to use the docker image? I dabbled and got stuck at `docker run alexgaynor/letsencrypt-aws update-certificates` which returns a `botocore.exceptions.NoRegionError: You must specify a region` that neither a `aws configure` nor a `export AWS_DEFAULT_REGION=xxx` managed to fix)

**Comment by alex** [comment]
This looks like you don't have `openssl-dev` installed.

On Mon, Mar 21, 2016 at 2:11 PM, Esardes notifications@github.com wrote:

> Hello
> sudo /usr/local/bin/pip install -r requirements.txt fails with what seems
> to be an openSSL issue
> 
> ` writing src/cryptography.egg-info/PKG-INFO
> writing top-level names to src/cryptography.egg-info/top_level.txt
> writing dependency_links to src/cryptography.egg-info/dependency_links.txt
> writing entry points to src/cryptography.egg-info/entry_points.txt
> warning: manifest_maker: standard file '-c' not found
> 
> reading manifest file 'src/cryptography.egg-info/SOURCES.txt'
> reading manifest template 'MANIFEST.in'
> no previously-included directories found matching 'docs/_build'
> warning: no previously-included files matching '*' found under directory 'vectors'
> writing manifest file 'src/cryptography.egg-info/SOURCES.txt'
> running build_ext
> generating cffi module 'build/temp.linux-x86_64-2.7/_padding.c'
> creating build/temp.linux-x86_64-2.7
> generating cffi module 'build/temp.linux-x86_64-2.7/_constant_time.c'
> generating cffi module 'build/temp.linux-x86_64-2.7/_openssl.c'
> building '_openssl' extension
> creating build/temp.linux-x86_64-2.7/build
> creating build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7
> gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/_openssl.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_openssl.o
> build/temp.linux-x86_64-2.7/_openssl.c:423:27: fatal error: openssl/e_os2.h: No such file or directory
>  #include <openssl/e_os2.h>
>                            ^
> compilation terminated.
> error: command 'gcc' failed with exit status 1
> 
> ---
> 
> Command "/usr/bin/python2.7 -u -c "import setuptools, tokenize;_file_='/tmp/pip-build-3NcnLy/cryptography/setup.py';exec(compile(getattr(tokenize,
> 'open', open)(_file_).read().replace('\r\n', '\n'), _file_, 'exec'))"
> install --record /tmp/pip-eE19gE-record/install-record.txt
> --single-version-externally-managed --compile" failed with error code 1 in
> /tmp/pip-build-3NcnLy/`
> 
> Thanks a lot for your help!
> (Alternatively, would you be kind to write a line in the README about how
> to use the docker image? I dabbled and got stuck at docker run
> alexgaynor/letsencrypt-aws update-certificates which returns a botocore.exceptions.NoRegionError:
> You must specify a region that neither a aws configure nor a export
> AWS_DEFAULT_REGION=xxx managed to fix)
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/alex/letsencrypt-aws/issues/37

## 

"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: D1B3 ADC0 E023 8CA6

**Comment by Esardes** [comment]
Yes thank you!
