### ISSUE TITLE
Problem with certificate and pem files

### ISSUE THREAD

**Issue by limbera** [alex/letsencrypt-aws#51]
I am struggling to see where this application generates the certificate? I have generated a pem file with the register command, but where do I actually get a certificate from?

**Comment by alex** [comment]
Certificates are generated internally and never stored on disk.

**Comment by limbera** [comment]
I see. So i should use lets encrypt to get a certificate first, then upload it, and this script will replace any expired ones? I may write an extension to do the initial creation part too - would that be something you'd like to extend this package with? @alex
