### ISSUE TITLE
Multiple domains?

### ISSUE THREAD

**Issue by jmvbxx** [alex/letsencrypt-aws#67]
I currently have an EC2 instance with nginx and I'm running Let's Encrypt every time a new domain is created.  Right now we have over 30 domains being hosted.  I use the `well-known` validation currently.

What's the best way to set this up on a new ELB?

From what I've read, I need to create an ELB and create an instance (for example) to run the `letsencrypt-aws` script.  Where do I specify all of the domains I already have certs for?

I'm clearly missing a piece of the puzzle :-)  Thanks in advance!

**Comment by alex** [comment]
The `hosts` key in the configuration is used, for example yours might look like:

``` json
{
    "domains": [
        {
            "elb": {
                "name": "my-elb"
            },
            "hosts": ["www.host.com", "www2.host.com", "www3.host8.org", "..."]
        }
    ]
}
```
