### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'iteritems'

### ISSUE THREAD

**Issue by vaindil** [alex/letsencrypt-aws#69]
Windows 10 x64, Python 3.5.2 x64. I cloned the repo and am trying to run the first command, `python letsencrypt-aws.py register me@example.com`, but I'm getting the error `AttributeError: 'dict' object has no attribute 'iteritems'`.

Here's the traceback:

```
Traceback (most recent call last):
  File "letsencrypt-aws.py", line 577, in <module>
    cli()
  File "C:\Users\Steven\AppData\Local\Programs\Python\Python35-32\lib\site-packages\click\core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Steven\AppData\Local\Programs\Python\Python35-32\lib\site-packages\click\core.py", line 696, in main
    rv = self.invoke(ctx)
  File "C:\Users\Steven\AppData\Local\Programs\Python\Python35-32\lib\site-packages\click\core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Steven\AppData\Local\Programs\Python\Python35-32\lib\site-packages\click\core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Steven\AppData\Local\Programs\Python\Python35-32\lib\site-packages\click\core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "letsencrypt-aws.py", line 559, in register
    logger.emit("acme-register.generate-key")
  File "letsencrypt-aws.py", line 38, in emit
    "{}={!r}".format(k, v) for k, v in data.iteritems()
AttributeError: 'dict' object has no attribute 'iteritems'
```

**Comment by alex** [comment]
Ooof, looks like a py3 bug slipped in (not sure I've ever tested with py3k
before); will try to fix later today.

On Thu, Jul 14, 2016 at 2:20 PM, Steven Hall notifications@github.com
wrote:

> Windows 10 x64, Python 3.5.2 x64. I cloned the repo and am trying to run
> the first command, python letsencrypt-aws.py register me@example.com, but
> I'm getting the error AttributeError: 'dict' object has no attribute
> 'iteritems'.
> 
> Here's the traceback:
> 
> Traceback (most recent call last):
>   File "letsencrypt-aws.py", line 577, in <module>
>     cli()
>   File "C:\Users\Steven\AppData\Local\Programs\Python\Python35-32\lib\site-packages\click\core.py", line 716, in **call**
>     return self.main(_args, *_kwargs)
>   File "C:\Users\Steven\AppData\Local\Programs\Python\Python35-32\lib\site-packages\click\core.py", line 696, in main
>     rv = self.invoke(ctx)
>   File "C:\Users\Steven\AppData\Local\Programs\Python\Python35-32\lib\site-packages\click\core.py", line 1060, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "C:\Users\Steven\AppData\Local\Programs\Python\Python35-32\lib\site-packages\click\core.py", line 889, in invoke
>     return ctx.invoke(self.callback, *_ctx.params)
>   File "C:\Users\Steven\AppData\Local\Programs\Python\Python35-32\lib\site-packages\click\core.py", line 534, in invoke
>     return callback(_args, **kwargs)
>   File "letsencrypt-aws.py", line 559, in register
>     logger.emit("acme-register.generate-key")
>   File "letsencrypt-aws.py", line 38, in emit
>     "{}={!r}".format(k, v) for k, v in data.iteritems()
> AttributeError: 'dict' object has no attribute 'iteritems'
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/alex/letsencrypt-aws/issues/69, or mute the thread
> https://github.com/notifications/unsubscribe/AAADBFb1bIfSxdtJ9I4OCRtPm2UOeJcmks5qVn3jgaJpZM4JMtVX
> .

## 

"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: D1B3 ADC0 E023 8CA6
