### ISSUE TITLE
Documentation with example

### ISSUE THREAD

**Issue by sincerekamal** [alex/letsencrypt-aws#73]
Hi,
I'm really poor in understanding how it works from the documentation. Could you explain it with an example ? And also I would like to know whether we need to do this process for ELB or for server domains.

For example,

**Domain name**: `api.myapp.com` (which is registered through different DNS provider, not route53)
**ELB Domain**: `app-prod-web-987654xxxxx.us-west-2.elb.amazonaws.com` (A Record)

**Comment by alex** [comment]
letsencrypt-aws currently requires you to have DNS configured through route-53

**Comment by sincerekamal** [comment]
Okay fine. At least provide an example for configuring with Route-53. Instead of just "string, integer" like that..
