### ISSUE TITLE
AttributeError: 'module' object has no attribute 'packages'

### ISSUE THREAD

**Issue by travis-edgar** [alex/letsencrypt-aws#80]
- On Ubuntu **14.04.5 LTS**
- Using Python **2.7.6**
- pip 8.1.2 from /usr/local/lib/python2.7/dist-packages (python 2.7)
- `pip install -r /opt/letsencrypt-aws/requirements.txt` successfull.
- Executing `python /opt/letsencrypt-aws/letsencrypt-aws.py update-certificates`

Receiving following error...

``` python
Traceback (most recent call last):
  File "letsencrypt-aws.py", line 8, in <module>
    import acme.client
  File "/opt/letsencrypt-aws/src/acme/acme/acme/client.py", line 29, in <module>
    requests.packages.urllib3.contrib.pyopenssl.inject_into_urllib3()
AttributeError: 'module' object has no attribute 'packages'
```

Read https://github.com/alex/letsencrypt-aws/issues/24, as mentioned above `pip install...` worked.

Cheers.

**Comment by alex** [comment]
This doesn't appear to be a letsecnrytp-aws bug.

**Comment by travis-edgar** [comment]
Agreed, thanks for looking.
