### ISSUE TITLE
Support the use of profiles and specified keys

### ISSUE THREAD

**Issue by simplesteph** [alex/letsencrypt-aws#82]
Hi,

I manage multiple AWS environments and would like to use letscrypt-aws for each of them. Right now it seems that only the "default" profile will be used because of this line:

`session = boto3.Session()` 
(https://github.com/alex/letsencrypt-aws/blob/master/letsencrypt-aws.py#L491)

It would be great to have the option to provide a profile_name or some aws keys as arguments when using the python script. The signature for session is here:

```
    def __init__(self, aws_access_key_id=None, aws_secret_access_key=None,
                 aws_session_token=None, region_name=None,
                 botocore_session=None, profile_name=None):
```

(http://boto3.readthedocs.io/en/latest/_modules/boto3/session.html)

I think it would highly benefit the project and allow more automation for end users.

**Comment by pugsley** [comment]
Hey @simplesteph simply set `AWS_PROFILE` before calling the script. Then you can use the credentials in your aws credentials file.

e.g. `AWS_PROFILE=xyz python letsencrypt-aws.py...`

**Comment by simplesteph** [comment]
You're right, this works. I personally find it a bit easier to provide it as a python option as it makes it a bit more implementation agnostic.
