### ISSUE TITLE
Access To Private Key

### ISSUE THREAD

**Issue by travis-edgar** [alex/letsencrypt-aws#85]
Is there any way we can get a copy of the private key used when creating the Lets Encrypt keys?

I see that the private key is needed when uploading the certificate to AWS however, I have not been able to find a way to access those keys once in IAM.

Thanks in advance.

**Comment by alex** [comment]
No, IAM does not let you download the private keys.

**Comment by travis-edgar** [comment]
Great, thanks. I may be a little confused, is the key returned from the 

```
python letsencrypt-aws.py register email@host.com
```

used as the private key when interacting with Let's Encrypt?

Ultimately I am after the private key used to create the certs.

Thanks.

**Comment by alex** [comment]
No, that private key is your let's encrypt account private key. It is used to authenticate API requests to let's encrypt, not for the TLS certs you get.

**Comment by travis-edgar** [comment]
The only way to get the private keys used then would be to extend your code such that it writes out the keys after it generates them? Updating...

```
generate_rsa_private_key()
```

And going against your design for creating keys in memory.
